---

##############################
### BEDROOM-MULTISENSORS ###
##############################


################
#### PINOUT ####
################

### TO BE DEFINED ###
### TO BE DEFINED ###
### TO BE DEFINED ###
### TO BE DEFINED ###
### TO BE DEFINED ###

#####################
### SUBSTITUTIONS ###
#####################

substitutions:
  device_name: "Bedroom Multisensor"
  device_id: "bedroom_multisensor"

###########################
### BOARD CONFIGURATION ###
###########################

esphome:
  name: bedroom-multisensor
  platform: ESP32
  board: esp32doit-devkit-v1
  comment: TEMP HUM PM 2.5 MOTION SENSOR 

#########################
### LOG CONFIGURATION ###
#########################

logger:
  level: DEBUG

##########################
### WIFI CONFIGURATION ###
##########################

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  domain: !secret domain
  ap:
    ssid: "${device_name} Hotspot"
    password: !secret hotspot_password

####################################
### CAPTIVE PORTAL CONFIGURATION ###
####################################

captive_portal:

#########################
### NTP CONFIGURATION ###
#########################

time:
  - platform: sntp
    id: sntp_time
    servers:
      - !secret ntp_server

#########################
### API CONFIGURATION ###
#########################

api:
  encryption:
    key: !secret api_key

#########################
### OTA CONFIGURATION ###
#########################

ota:
  - platform: esphome
    password: !secret ota_password

#################################
### TEXT SENSOR CONFIGURATION ###
#################################

text_sensor:

  ### FIRMWARE VERSION ###

  - platform: version
    name: "${device_name} Version"
    id: "${device_id}_version"
    icon: "mdi:all-inclusive-box"
    hide_timestamp: true

  ### IP ADDRESS ###

  - platform: wifi_info
    ip_address:
      name: "${device_name} IP"
      id: "${device_id}_ip"
      icon: mdi:ip-network 

################################
### WEB SERVER CONFIGURATION ###
################################

web_server:
  port: !secret web_server_port
  ota: true
  local: true
  version: 2
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

#########################    
### I2C CONFIGURATION ###
#########################

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: false

switch:

  ### RESTART ###

  - platform: restart
    name: "${device_name} Restart"

  ### RESTART SAFE MODE ###  

  - platform: safe_mode
    name: "${device_name} Restart (Safe Mode OTA)"

esp32_ble_tracker:
  scan_parameters:
    active: true
  
binary_sensor:

 ### BLE TRACKING ###

  - platform: ble_presence
    mac_address: !secret mac_amazfit_sandro
    name: "${device_name} Amazfit Bip Sandro"

 ### MOTION LEFT ###

  - platform: gpio
    pin: GPIO33
    name: "${device_name} Motion Left"
    device_class: motion

 ### MOTION RIGHT ###

  - platform: gpio
    pin: GPIO32
    name: "${device_name} Motion Right"
    device_class: motion

sensor:

  ### WIFI SIGNAL ###

  - platform: wifi_signal
    name: "Study Powerstrip WiFi Signal"
    update_interval: 60s

  ### BLE SIGNAL ###

  - platform: ble_rssi
    mac_address: !secret mac_amazfit_sandro
    name: "${device_name} Amazfit Bip Sandro RSSI"
 
 ### TEMPERATURE AND HUMIDITY ### 

  - platform: aht10
    address: 0x38
    temperature:
      name: "${device_name} Temperature"
      id: "${device_id}_temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      filters:
        offset: -2      
      icon: "mdi:temperature-celsius"
    humidity:
      name: "${device_name} Humidity"
      id: "${device_id}_humidity"
      icon: "mdi:water-percent"
    update_interval: 300s

  - platform: template
    name: "${device_name} Board Temperature"
    id: "${device_id}_temp"
    lambda: return temperatureRead();
    unit_of_measurement: "°C"
    update_interval: 1800s

  - platform: xiaomi_miscale
    mac_address: !secret mac_miscale
    weight:
      name: "Xiaomi Mi Scale Weight"
    impedance:
      name: "Xiaomi Mi Scale Impedance"

  ### UPTIME ###
  
  - platform: uptime
    type: seconds
    name: Uptime Sensor
...

### EOF ###