---
##############################
### OPENSPACE-MULTISENSORS ###
##############################


################
#### PINOUT ####
################

### D3 --> VINDRIKTNING BOARD    ###
### D7 --> AM312 MOTION SENSOR   ###
### A0 --> TEMT6000 LIGHT SENSOR ###
### D2 --> AHT10 SDA             ###
### D1 --> AHT10 SCL             ###

#####################
### SUBSTITUTIONS ###
#####################

#substitutions:
#  device_name: "Study Multisensor"
#  device_id: "study_multisensor"

###########################
### BOARD CONFIGURATION ###
###########################

esphome:
  name: openspace-multisensor
  comment: TEMP HUM PM 2.5 MOTION SENSOR
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: false
 
#########################
### LOG CONFIGURATION ###
#########################

logger:
  level: INFO
  
################################
### STATUS LED CONFIGURATION ###
################################

status_led:
  pin:
    number: D4
    inverted: true

##########################
### WIFI CONFIGURATION ###
##########################

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  domain: !secret domain
  ap:
    ssid: "Openspace Multisensor Hotspot"
    password: !secret hotspot_password

####################################
### CAPTIVE PORTAL CONFIGURATION ###
####################################

captive_portal:

#########################
### NTP CONFIGURATION ###
#########################

time:
  - platform: sntp
    id: sntp_time
    servers:
      - !secret ntp_server

#########################
### API CONFIGURATION ###
#########################

api:
  encryption:
    key: !secret api_key

#########################
### OTA CONFIGURATION ###
#########################

ota:
  password: !secret ota_password

#################################
### TEXT SENSOR CONFIGURATION ###
#################################

text_sensor:

  ### FIRMWARE VERSION ###

  - platform: version
    name: "Openspace Multisensor Version"
    id: openspace_version
    icon: "mdi:all-inclusive-box"
    hide_timestamp: true

  ### IP ADDRESS ###

  - platform: wifi_info
    ip_address:
      name: "OpenSpace Multisensor IP"
      id: openspace_ip
      icon: mdi:ip-network
    mac_address:
      name: "OpenSpace Multisensor Wifi MAC Address"
      id: openspace_macaddress
      icon: mdi:expansion-card

################################
### WEB SERVER CONFIGURATION ###
################################

web_server:
  port: !secret web_server_port
  #local: true
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

#########################    
### I2C CONFIGURATION ###
#########################

i2c:
  sda: D2
  scl: D1
  scan: false

##########################
### UART CONFIGURATION ###
##########################

uart:
  rx_pin: D3
  id: uart1
  baud_rate: 9600

############################
### SENSOR CONFIGURATION ###
############################

sensor:

  ### WIFI SIGNAL ###

  - platform: wifi_signal
    name: "Openspace Multisensor WiFi Signal"
    update_interval: 60s

  ### TEMPERATURE AND HUMIDITY ### 

  - platform: aht10
    address: 0x38
    temperature:
      name: "Openspace Temperature"
      id: openspace_temperature
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      icon: "mdi:temperature-celsius"
    humidity:
      name: "Openspace Humidity"
      id: openspace_humidity
      icon: "mdi:water-percent"
    update_interval: 300s

  ### PM 2.5 ###

  - platform: pm1006
    pm_2_5:
      name: "Openspace PM2.5"
      icon: "mdi:blur"

  ### BRIGHTNESS ###
    
  - platform: adc
    pin: A0
    name: "Openspace Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;
    update_interval: 1s

###################################
### BINARY SENSOR CONFIGURATION ###
###################################

binary_sensor:

 ### MOTION ###

  - platform: gpio
    pin: D7
    name: "Openspace Motion"
    device_class: motion

##############################
### SWITCHES CONFIGURATION ###
##############################

switch:

  ### RESTART ###

  - platform: restart
    name: "Openspace Restart"

  ### RESTART SAFE MODE ###  

  - platform: safe_mode
    name: "Openspace Restart (Safe Mode OTA)"

...

### EOF ###