---
##############################
### OPENSPACE-MULTISENSORS ###
##############################

#### PINOUT ####

### D3 --> VINDRIKTNING BOARD    ###
### D7 --> AM312 MOTION SENSOR   ###
### A0 --> TEMT6000 LIGHT SENSOR ###
### D2 --> AHT10 SDA             ###
### D1 --> AHT10 SCL             ###

### DEFINE BOARD HARDWARE ###

esphome:
  name: openspace-multisensor
  comment: Openspace Multisensor ( TEMP HUM PM 2.5 MOTION )
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: true
  
### ENABLE LOGGING ###

logger:
  level: DEBUG

### STATUS LED ###

status_led:
  pin:
    number: D4
    inverted: true

### WIFI SETTINGS ###

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  domain: !secret domain

### TIME SYNC ###

time:
  - platform: sntp
    id: sntp_time
    servers:
      - !secret ntp_server

### ENABLE HOME ASSISTANT API ###

api:
  password: !secret api_password

### ENABLE OTA ###

ota:
  password: !secret ota_password

### FIRMWARE VERSION ###

text_sensor:

### ESPHOME FIRMWARE VERSION ###

  - platform: version
    name: "Openspace Multisensor Version"
    id: openspace_version

### IP ADDRESS ###

  - platform: wifi_info
    ip_address:
      name: "OpenSpace Multisensor IP"
      id: openspace_ip  

### ENABLE WEB SERVER ###

web_server:
  port: !secret web_server_port
  local: true
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
    
### ENABLE I2C WITH AUTOSCAN ###

i2c:
  sda: D2
  scl: D1
  scan: false

### ENABLE UART TO IKEA BOARD ###

uart:
  rx_pin: D3
  id: uart1
  baud_rate: 9600

### SENSOR CONFIGURATION ###

sensor:

  ### WIFI SIGNAL ###

  - platform: wifi_signal
    name: "Openspace Multisensor WiFi Signal"
    update_interval: 60s

  ### TEMPERATURE AND HUMIDITY ### 

  - platform: aht10
    address: 0x38
    temperature:
      name: "Openspace Temperature"
      id: openspace_temperature
    humidity:
      name: "Openspace Humidity"
      id: openspace_humidity
    update_interval: 600s

  ### PM 2.5 ###

  - platform: pm1006
    pm_2_5:
      name: "Openspace PM2.5"

  ### BRIGHTNESS ###
    
  - platform: adc
    pin: A0
    name: "Openspace Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;
    update_interval: 1s

### MOTION ###
    
binary_sensor:
  - platform: gpio
    pin: D7
    name: "Openspace Motion"
    device_class: motion

### SWITCHES ###

switch:

  ### RESTART ###

  - platform: restart
    name: "Openspace Restart"

  ### RESTART SAFE MODE ###  

  - platform: safe_mode
    name: "Openspace Restart (Safe Mode OTA)"

...

### EOF ###