---
###############################
###     STUDY-POWERSTRIP    ###
###############################

#### PINOUT KLOE 4 ####

### Power Button --> GPIO03 
### Green LED --> GPIO1  
### Relay 1 --> GPIO05 
### Relay 2 --> GPIO04 
### Relay 3 --> GPIO12 
### Relay 4 --> GPIO13 
### Relay 5 --> GPIO14 

### DEFINE BOARD HARDWARE ###

esphome:
  name: study-powerstrip
  comment: Study Powerstrip
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: false
  
### ENABLE LOGGING ###

logger:
  level: DEBUG

### STATUS LED ###

status_led:
  pin:
    number: GPIO1
    inverted: True

### WIFI SETTINGS ###

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  domain: !secret domain
  ap:
    ssid: "Study Powerstrip Fallback Hotspot"
    password: !secret hotspot_password

### ENABLE WIFI CAPTIVE PORTAL IF SOMETHING GO WRONG ###

captive_portal:

### TIME SYNC ###

time:
  - platform: sntp
    id: sntp_time
    servers:
      - !secret ntp_server

### ENABLE HOME ASSISTANT API ###

api:
  password: !secret api_password

### ENABLE OTA ###

ota:
  password: !secret ota_password

### FIRMWARE VERSION ###

text_sensor:

### ESPHOME FIRMWARE VERSION ###

  - platform: version
    name: "Study Powerstrip Version"
    id: study_powerstrip_version

### IP ADDRESS ###

  - platform: wifi_info
    ip_address:
      name: "Study Powerstrip IP"
      id: study_powerstrip_ip  

### ENABLE WEB SERVER ###

web_server:
  port: !secret web_server_port
  local: true
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

### SENSOR CONFIGURATION ###

sensor:

  ### WIFI SIGNAL ###

  - platform: wifi_signal
    name: "Study Powerstrip WiFi Signal"
    update_interval: 60s

binary_sensor:

  ### POWER BUTTON RELATED ACTION ###

  - platform: gpio
    id: power_button
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay_1
      - switch.toggle: relay_2
      - switch.toggle: relay_3
      - switch.toggle: relay_4
      - switch.toggle: relay_5
    filters:
      - delayed_on: 10ms

### SWITCHES ###

switch:

  - platform: gpio
    name: Study Powerstrip Relay 1
    id: relay_1
    pin: GPIO05
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: Study Powerstrip Relay 2
    id: relay_2
    pin: GPIO04
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: Study Powerstrip Relay 3 
    id: relay_3
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: Study Powerstrip Relay 4
    id: relay_4
    pin: GPIO13
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: Study Powerstrip Relay 5
    id: relay_5
    pin: GPIO14
    restore_mode: RESTORE_DEFAULT_OFF

  ### RESTART ###

  - platform: restart
    name: "Study Powerstrip Restart"

  ### RESTART SAFE MODE ###  

  - platform: safe_mode
    name: "Study Powerstrip Restart (Safe Mode OTA)"

...

### EOF ###