---
##############################
### STUDY-POWERSTRIP ###
##############################


################
#### PINOUT ####
################

### Power Button --> GPIO03 --> TOGGLE ALL RELAY ###
### Green LED --> GPIO1 --> POWER INDICATOR      ###
### Relay 1 --> GPIO05 --> MONITOR               ###
### Relay 2 --> GPIO04 --> LAPTOP                ###
### Relay 3 --> GPIO12 --> MI DESK LAMP 2        ###
### Relay 4 --> GPIO13 --> NEST HUB 2            ###
### Relay 5 --> GPIO14 --> USB PORTS             ###


###########################
### BOARD CONFIGURATION ###
###########################

esphome:
  name: study-powerstrip
  comment: MONITOR,POWERSUPPLY,LAMP,NEST HUB 2, USB
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: false

#########################
### LOG CONFIGURATION ###
#########################

logger:
  level: INFO

################################
### STATUS LED CONFIGURATION ###
################################

status_led:
  pin:
    number: GPIO1
    inverted: true

##########################
### WIFI CONFIGURATION ###
##########################

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  domain: !secret domain
  ap:
    ssid: "Study Powerstrip Hotspot"
    password: !secret hotspot_password

####################################
### CAPTIVE PORTAL CONFIGURATION ###
####################################

captive_portal:

#########################
### NTP CONFIGURATION ###
#########################

time:
  - platform: sntp
    id: sntp_time
    servers:
      - !secret ntp_server

#########################
### API CONFIGURATION ###
#########################

api:
  encryption:
    key: !secret api_key

#########################
### OTA CONFIGURATION ###
#########################

ota:
  password: !secret ota_password

#################################
### TEXT SENSOR CONFIGURATION ###
#################################

text_sensor:

  ### FIRMWARE VERSION ###

  - platform: version
    name: "Study Powerstrip Version"
    id: study_powerstrip_version
    hide_timestamp: true
    icon: "mdi:all-inclusive-box"

  ### IP ADDRESS ###

  - platform: wifi_info
    ip_address:
      name: "Study Powerstrip IP"
      id: study_powerstrip_ip
      icon: mdi:ip-network 
    mac_address:
      name: "Study Powerstrip Wifi MAC Address"
      id: openspace_macaddress
      icon: mdi:expansion-card

################################
### WEB SERVER CONFIGURATION ###
################################

web_server:
  port: !secret web_server_port
  #local: true
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

############################
### SENSOR CONFIGURATION ###
############################

sensor:

  ### WIFI SIGNAL ###

  - platform: wifi_signal
    name: "Study Powerstrip WiFi Signal"
    update_interval: 60s

###################################
### BINARY SENSOR CONFIGURATION ###
###################################

binary_sensor:

  ### POWER BUTTON ###

  - platform: gpio
    id: power_button
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay_1
      - switch.toggle: relay_2
      - switch.toggle: relay_3
      - switch.toggle: relay_4
      - switch.toggle: relay_5
    filters:
      - delayed_on: 10ms

##############################
### SWITCHES CONFIGURATION ###
##############################

switch:

  ### MONITOR ###

  - platform: gpio
    name: monitor
    id: relay_1
    pin: GPIO05
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:monitor
  
  ### LAPTOP ###

  - platform: gpio
    name: laptop
    id: relay_2
    pin: GPIO04
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:laptop

  ### MI DESK LAMP 2 ###
 
  - platform: gpio
    name: mi desk lamp 2
    id: relay_3
    pin: GPIO12
    restore_mode: ALWAYS_ON
    icon: mdi:desk-lamp

  ### NEST HUB 2 ###

  - platform: gpio
    name: nest hub 2
    id: relay_4
    pin: GPIO13
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:tablet

  ### USB ###
  
  - platform: gpio
    name: usb study
    id: relay_5
    pin: GPIO14
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:usb

  ### RESTART ###

  - platform: restart
    name: "Openspace Restart"

  ### RESTART SAFE MODE ###  

  - platform: safe_mode
    name: "Openspace Restart (Safe Mode OTA)"

...

### EOF ###